name: PR Comment Test

permissions:
   contents: read
   issues: write
   pull-requests: write
   
on:
  workflow_dispatch:

jobs:
  comment-test:
    name: Comment Test
    runs-on: ubuntu-latest

    env:
      MY_MESSAGE: |
        This is a multi-line message.
        It can span multiple lines.

    steps:
      - name: Simulate output
        id: simulate
        run: |
          echo "directoryA=ayee" >> $GITHUB_OUTPUT
          echo "directoryB=uyee" >> $GITHUB_OUTPUT
          echo "today=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
          
      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
           issue-number: 2
           comment-author: 'github-actions[bot]'
           body-includes: Plan ${{ steps.simulate.outputs.directoryA }}

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: 2
          body: |
            Plan ${{ steps.simulate.outputs.directoryA }}
            Test message
            ${{ env.MY_MESSAGE }}

            Updated: ${{ steps.simulate.outputs.today }}
          edit-mode: replace
