name: Terraform plan diff

permissions:
   contents: read
   issues: write
   pull-requests: write
   
on:
  workflow_dispatch:

jobs:
  comment-test:
    name: Comment Test
    runs-on: ubuntu-latest

    env:
      SAMPLE_EMPTY: |
        An execution plan has been generated and is shown below.
        Resource actions are indicated with the following symbols:
        
        Terraform will perform the following actions:
        
        Plan: 0 to add, 0 to change, 0 to destroy.
      SAMPLE_ADD_UPDATE: |
        Terraform used the selected providers to generate the following execution
        plan. Resource actions are indicated with the following symbols:
          ~ update in-place
        
        Terraform will perform the following actions:
          # module.main.aws_security_group_rule.allow_a_to_b will be created
          + resource "aws_security_group_rule" "allow_a_to_b" {
              + description              = "ingress from a to b"
              + from_port                = 443
              + id                       = (known after apply)
              + protocol                 = "tcp"
              + security_group_id        = "sg-123abc"
              + self                     = false
              + source_security_group_id = "sg-456def"
              + to_port                  = 443
              + type                     = "ingress"
            }
        
          # aws_s3_bucket.example will be updated in-place
          ~ resource "aws_s3_bucket" "example" {
                id                          = "test-bucket"
              ~ tags                        = {
                    "Description" = "Test bucket"
                  ~ "Dummy"       = "value3" -> "value34"
                    "Environment" = "testing"
                    "Name"        = "test-bucket"
                }
              ~ tags_all                    = {
                  ~ "Dummy"       = "value3" -> "value34"
                    # (3 unchanged elements hidden)
                }
                # (9 unchanged attributes hidden)
        
                # (3 unchanged blocks hidden)
            }
        
        Plan: 0 to add, 1 to change, 0 to destroy.
          
      SAMPLE_UPDATE: |
        Terraform used the selected providers to generate the following execution
        plan. Resource actions are indicated with the following symbols:
          ~ update in-place
        
        Terraform will perform the following actions:
        
          # aws_s3_bucket.example will be updated in-place
          ~ resource "aws_s3_bucket" "example" {
                id                          = "test-bucket"
              ~ tags                        = {
                    "Description" = "Test bucket"
                  ~ "Dummy"       = "value3" -> "value34"
                    "Environment" = "testing"
                    "Name"        = "test-bucket"
                }
              ~ tags_all                    = {
                  ~ "Dummy"       = "value3" -> "value34"
                    # (3 unchanged elements hidden)
                }
                # (9 unchanged attributes hidden)
        
                # (3 unchanged blocks hidden)
            }
        
        Plan: 0 to add, 1 to change, 0 to destroy.

        
    steps:
      # - name: Diff empty
      - name: Diff ADD UPDATE
        shell: bash
        run: |
          # Diff Markdown regexes
          diffKeywordRegex="^( +)([-+~]\s)(.*)(\s=\s|\s->\s|<<|\{|\(known after apply\)| {2,}[^ ]+:.*)(.*)"
          diffListRegex="^( +)([-+~]\s)\".*\","
          diffTildeRegex="^~"
          
          # Example usage
          formattedOutput=$(echo "$SAMPLE_ADD_UPDATE" | sed -E "s/$diffKeywordRegex/\2\1\3\4\5/g")
          formattedOutput=$(echo "$formattedOutput" | sed -E "s/$diffListRegex/\2\1\3/g")
          formattedOutput=$(echo "$formattedOutput" | sed -E "s/$diffTildeRegex/!/g")
          
          echo "$formattedOutput"
